#include "arduino_secrets.h"
/*
Sketch generated by the Arduino IoT Cloud Thing "Untitled"
https://create.arduino.cc/cloud/things/8ad26a5e-d53a-4fe2-84be-44941b36ec28

Arduino IoT Cloud Variables description

The following variables are automatically generated and updated when changes are made to the Thing

CloudTemperatureSensor temp;
bool led;

Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
which are called when their values are changed from the Dashboard.
These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"
DHT dht(D4,DHT22);

void setup() {
// Initialize serial and wait for port to open:
pinMode(D2,OUTPUT);
dht.begin();
Serial.begin(9600);
// This delay gives the chance to wait for a Serial Monitor without blocking if none is found
delay(1500);

// Defined in thingProperties.h
initProperties();

// Connect to Arduino IoT Cloud
ArduinoCloud.begin(ArduinoIoTPreferredConnection);
/*
The following function allows you to obtain more information
related to the state of network and IoT Cloud connection and errors
the higher number the more granular information you'll get.
The default is 0 (only errors).
Maximum is 4
*/
setDebugMessageLevel(2);
ArduinoCloud.printDebugInfo();
}

void loop() {
ArduinoCloud.update();
// Your code here
sendData();
}

void sendData()
{
float data = dht.readTemperature();
temp=data;
Serial.print("The Temperature is");Serial.print(data);Serial.println("Deg C");
delay(1000);
}

/*
Since Led is READ_WRITE variable, onLedChange() is
executed every time a new value is received from IoT Cloud.
*/
void onLedChange() {
// Add your code here to act upon Led change
if (led==1)
digitalWrite(D2,HIGH);
else
digitalWrite(D2,LOW);
}